# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Lab9test' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'lab9test' do
    @driver.get('http://localhost:3000/')
    @driver.manage.resize_to(1124, 550)
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys('1234')
    @driver.find_element(:id, 'btn').click
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys('12340')
    @driver.find_element(:id, 'btn').click
  end
end
